### ISSUE TITLE
Add instructions on how to trigger the action

### ISSUE THREAD

**Issue by GeckoEidechse** [GreenTF/NSModTemplate#2]
New modders are general less familiar with GitHub Actions and as such likely not able to tell what actually triggers the action.

As such it might be helpful to state that one needs to create a release on GitHub in order for the action to trigger and upload the files.

**Comment by AnActualEmerald** [comment]
~~not me doing this almost a year later~~ I think d28293120ccf92c8f2bcb0ba0ab6998978e3f992 shoud cover this?

**Comment by GeckoEidechse** [comment]
I'd say so, yeah. Thanks for adding <3
